### ISSUE TITLE
Implement automated performance testing

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#141]
@kyleabeauchamp has a benchmark script written already that could be adapted:
https://github.com/choderalab/pymbar/blob/master/scripts/benchmark_mbar.py

We agreed to punt this to the future.

**Comment by jchodera** [comment]
This was mentioned in #137

**Comment by jchodera** [comment]
I have a draft of this in place:
https://jenkins.choderalab.org/job/benchmark-pymbar-github-osx

It will run every time there is a master commit.

Should serve our purposes for now.

**Comment by jchodera** [comment]
Closing this for now, since we've decided to punt potentially indefinitely.

**Comment by mrshirts** [comment]
If we are writing an implementation paper in the very near future, then we will need to report on the efficiency.

**Comment by jchodera** [comment]
> If we are writing an implementation paper in the very near future, then we will need to report on the efficiency.

Yes, but @kyleabeauchamp made the point that we have a script to do that:
https://github.com/choderalab/pymbar/blob/master/scripts/benchmark_mbar.py

We don't need to automate it to run for every commit in order to benchmark things for the manuscript.

**Comment by mrshirts** [comment]
I am in agreement that automatically triggered performance tests don't make that much sense.
