### ISSUE TITLE
Add Python 3.3 tests to travis-ci?

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#160]
Looks like travis is only testing python 2.7 and 3.4:
https://github.com/choderalab/pymbar/blob/master/.travis.yml#L17-L18

Or are we skipping 3.3 support?

**Comment by kyleabeauchamp** [comment]
I'm fine with focusing on 27 and 34.

**Comment by jchodera** [comment]
We should probably make this an omnia-wide decision.

**Comment by jchodera** [comment]
https://github.com/omnia-md/conda-recipes/issues/119

**Comment by kyleabeauchamp** [comment]
Fixed by #163
