### ISSUE TITLE
detect_equilibration_binary_search is not memory safe

### ISSUE THREAD

**Issue by smcantab** [choderalab/pymbar#168]
today my cluster administrator has shut down 2 nodes because my jobs using detect_equilibration_binary_search had filled 100% of the memory and were swapping dangerously with the disk. I spent the afternoon looking into it and I have narrowed down the problem to the implementation of np.fft which is called by statsmodel through sm.tsa.stattools.acf. 

Turns out that "fft stores a cache of working memory for different sizes of fft's, so you can run into memory problems if you call this too many times with too many different n's", which is exactly what we do during the binary search. 

I have added my 2 cents to [an issue](https://github.com/numpy/numpy/issues/1864#issuecomment-71480635) that I found in the numpy github repo. My solution at the moment is to add a call to 
```python
np.fft.fftpack._fft_cache.clear()
```
which clears the global variable ```_fft_cache``` after each for loop or after each iteration. Would you be interested in a PR that addresses this issue?

**Comment by kyleabeauchamp** [comment]
I think that sounds like a reasonable workaround.

**Comment by smcantab** [comment]
it is necessary to clear the cache after every fft call, so I have added the necessary lines to the statisticalInefficiency_fft function in PR #169

**Comment by smcantab** [comment]
P.S. tests pass locally

**Comment by kyleabeauchamp** [comment]
Thanks!

**Comment by smcantab** [comment]
Thanks for merging!
