### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by gfzhou** [choderalab/pymbar#173]
Hi,
I think the default mode for testsystems.HarmonicOscillatorsTestCase().sample() should be 'u_kln' and it says so in DocStrings but the default is mistakenly set to 'u_kn' and the usage also uses mode 'u_kn' as default i.e. x_kn, u_kn, N_k, s_n = testsystems.HarmonicOscillatorsTestCase().sample(). 
I tried the conda version and it uses the 'u_kln' as default. So could you double check with it? 
Thanks.

**Comment by jchodera** [comment]
Thanks for bringing this to our attention, @gfzhou!  Can you clarify what branch you're talking about, and maybe give a link to the specific code in question in the repo?

**Comment by gfzhou** [comment]
Sorry for the unclear part. Here is the link to the script: https://github.com/choderalab/pymbar/blob/master/pymbar/testsystems/harmonic_oscillators.py
The function def sample(self, N_k=[10, 20, 30, 40, 50], mode='u_kn') should be changed to def sample(self, N_k=[10, 20, 30, 40, 50], mode='u_kln')

**Comment by jchodera** [comment]
Ah!  This line in the master branch?
https://github.com/choderalab/pymbar/blob/master/pymbar/testsystems/harmonic_oscillators.py#L100

**Comment by gfzhou** [comment]
Yes, master branch. Also I think the usage in the main page should also be changed accordingly.

**Comment by jchodera** [comment]
Main page?

**Comment by gfzhou** [comment]
Oh, sorry, I mean the README file in the master branch. 
https://github.com/choderalab/pymbar/blob/master/README.md

**Comment by kyleabeauchamp** [comment]
So one of the changes in pymbar3 is that we're trying to adopt the `u_kn` representation whenever possible because it can be considerably more memory efficient.  

Would you be satisfied if we just adjusted the docstring to report the default of "u_kln"?  That would require no changes to the actual code, just an updated docstring for self-consistency.

**Comment by gfzhou** [comment]
Yes, I have no problem as long as they are self-consistent. And I am looking forward to the pymbar3.

**Comment by kyleabeauchamp** [comment]
Should be fixed now by #176, thanks for the bug report!
