### ISSUE TITLE
Is there automated testing? Include alchemical-analysis in automated testing?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/pymbar#182]
Is there automated testing of modules in pymbar in any form? If so, we should figure out if/how alchemical-analysis.py can be included in automated testing so that we'll find out if any updates to the rest of pymbar break the tool.

**Comment by kyleabeauchamp** [comment]
Yes, most of pymbar is tested via nose tests located here:

https://github.com/choderalab/pymbar/tree/master/pymbar/tests

The scripts are still not being tested automatically

**Comment by davidlmobley** [comment]
I'm not familiar with "nose tests" yet. I'm assuming these are just
automated tests which look at whether the expected result is obtained in
test cases? If so then I should start a separate issue to add a test for
alchemical-analysis which looks at whether it generates the expected output
on test data. Can this be handled in the same framework?

On Wed, Apr 22, 2015 at 11:44 AM, Kyle Beauchamp <notifications@github.com>
wrote:

> Yes, most of pymbar is tested via nose tests located here:
>
> https://github.com/choderalab/pymbar/tree/master/pymbar/tests
>
> The scripts are still not being tested automatically
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/pymbar/issues/182#issuecomment-95297635>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
Yeah, these are generally automated results that do sanity checking or checking for an expected result.  

I'm not 100% sure how to best implement script testing to our automated testing framework, so we may have to brainstorm.

**Comment by jchodera** [comment]
Where *is* `alchemical-analysis.py` and what does it do?  Also, who is responsible for its maintenance?

**Comment by davidlmobley** [comment]
`pymbar/examples/alchemical-free-energy`. And, you've read the paper describing what it does - for example, you requested we add Kyle to the acknowledgments (http://link.springer.com/article/10.1007/s10822-015-9840-9/fulltext.html). Pavel should be responsible for its maintenance but so far fixes have all been handled through @mrshirts. I had thought this was because of GitHub learning curve issues, but apparently @FEPAnalysis (Pavel) does not have permission to merge pull requests. 

If you prefer, alchemical-analysis could certainly be split off into a separate project.

**Comment by jchodera** [comment]
I think this feature should be split out into a different repo that you control.  We can still automatically package it via conda, but it's going to be a lot better if you have primary control over this and it is a stand-alone thing that stands separate from `pymbar`.

You can certainly use `pymbar` as a dependency, and you can include this in both `setup.py` and the conda recipe so that `pymbar` is automatically installed when you install your tool.

**Comment by davidlmobley** [comment]
@mrshirts - do you have an issues with that? You were the one who wanted this to remain in pymbar (though that was long, long ago, before it moved into GitHub, so I can certainly see why things may have changed).

**Comment by davidlmobley** [comment]
I talked with @mrshirts and he agreed to splitting it off. I'll do so and then he will work to get pymbar documentation/GitHub/links updated to reflect the new location.

**Comment by davidlmobley** [comment]
(Marking as closed.)

**Comment by jchodera** [comment]
Sounds good!
