### ISSUE TITLE
alchemical analysis crashes when calc-lambda-neighbors=1

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/pymbar#183]
If the user performs a simulation with `calc-lambda-neighbors = 1`, the script correctly detects that it can't do MBAR, but will attempt to calculate using other methods. But, it crashes when trying to do the following in slice_data:

    u_klt[state, s1:s2, :nsnapshots[state]] = P.beta * ( data[r1:r2, :] + data[-1,:] )

[The full error is here.](https://gist.githubusercontent.com/wesbarnett/2a3d6677378f30c5e2dd/raw/db3b3eb04ea37c9fe1d1d210b704b14b0201f3f2/slice-data-error.txt)

**Comment by davidlmobley** [comment]
We've moved this to https://github.com/mobleylab/alchemical-analysis and hopefully will have a fix there. We decided the workflow would be easier going forwards if alchemical-analysis is separated from pymbar. Thanks for your input and hopefully we'll have a fix soon (or submit a Pull Request there if you have one).

**Comment by davidlmobley** [comment]
We believe this was fixed by https://github.com/MobleyLab/alchemical-analysis/pull/12. This issue can be closed and any further issues relating to this can be on the alchemical-analysis GitHub site.
