### ISSUE TITLE
Overflow in BAR when using 1-1-48 soft-core in solvation simulations

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/pymbar#185]
The pymbar implementation of BAR complains "The input data results in overflow in BAR" for solvation simulations when using a [soft-core potential of the 1-1-48 form](http://dx.doi.org/10.1063/1.3697833), as implemented in GROMACS. The GROMACS analysis tool "gmx bar" doesn't have this problem and is able to calculate the results.

In particular I simulated TraPPe-UA methane and ethane in TIP4P/2005 water at 0.1 vdw-lambda increments (from turned off to completely turned on at lambda=1) using the 1-1-48 soft-core potential. MBAR itself gives a result that is consistent with what is expected (as do other methods); however BAR conks out with overflow errors at states 9 -- 10 in both methane and ethane cases and just outputs zero. When using the standard soft-core potential in GROMACS, pymbar's BAR does fine. This overflow problem only happens with the 1-1-48 soft-core potential with free energy of solvation simulations. A simulation of transforming a group to another using the 1-1-48 soft core potential does not result in BAR overflow errors. Again, GROMAC's "gmx bar" handles the results here fine.

**Comment by jchodera** [comment]
Should be simple to fix! Can you post some problematic test data?

**Comment by wesbarnett** [comment]
Great! [Here's the methane data.](https://wavetulane-my.sharepoint.com/personal/jbarnet4_tulane_edu/_layouts/15/guestaccess.aspx?guestaccesstoken=kIvO4%2bUhoWlLCNRKW3k3S9%2finxFv%2bBt7Vyufh8TLmhw%3d&docid=046010034ef1b4c9ba4631ccec1ecc65d)

**Comment by mrshirts** [comment]
Wes, are you using the alchemical-gromacs.py driver to do this, or did you write your own driver?

**Comment by wesbarnett** [comment]
@mrshirts I used the alchemical-analysis.py script.

**Comment by mrshirts** [comment]
Great, that will make it easy to replicate any issues.

**Comment by jchodera** [comment]
Here is the test script I used:
https://gist.github.com/jchodera/33624ca0c37c7e2baff4

**Comment by mrshirts** [comment]
OK, I see where the issue is.  I'll need to cogitate a bit about how to fix it.
