### ISSUE TITLE
Some tests failing but not caught by travis?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/pymbar#190]
It seems that some of the built-in tests currently fail on my machine, though I haven't had a chance yet to investigate why travis isn't catching this. Specifically, 

```
>>> import test_mbar
>>> test_mbar.test_mbar_computeOverlap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_mbar.py", line 214, in test_mbar_computeOverlap
    x_n, u_kn, N_k_output, s_n = test.sample(even_N_k, mode='u_kn')
ValueError: need more than 3 values to unpack
```

I was trying to run this specific test as the `mbar.computeOverlap()` function seems to return a single argument now, whereas the test code assumes three arguments are returned: `overlap_scalar, eigenval, O = mbar.computeOverlap()`, so it looked like it should fail. However, the test doesn't even get that far.

I'm assuming there were API changes to a couple of the functions and the tests weren't updated to reflect this, though as I said I haven't checked to see why automated testing is not catching this (I have leave for the day). I did notice that travis-ci reports that the test_mbar_computeOverlap test is `ok`, so I'm very puzzled.

Background as to why I'm poking into this: I ran into an issue with alchemical-analysis where apparently the API for `mbar.computeOverlap` changed without us catching it so that it now returns something different by default. I went looking to try and find when this was changed and how, and in the process stumbled across this test function which looked like it should fail since it still uses `mbar.computeOverlap` in the same way we were using it.

**Comment by kyleabeauchamp** [comment]
So regarding the test: have you tested the version of pymbar used in your current python session?  To me, this looks like a possible issue with multiple cached versions.

Regarding the API change, this is again one of the few instances where we elected to get rid of variable length lists as the standard way of passing outputs.

**Comment by kyleabeauchamp** [comment]
On my machine, your code works fine:

```
In [1]: import test_mbar

In [2]: test_mbar.test_mbar_computeOverlap()
/home/kyleb/opt/lib/python2.7/site-packages/scipy/optimize/minpack.py:237: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)
```

**Comment by davidlmobley** [comment]
Hah - looks like I'd forgotten to go back to the main branch after conda
installing the other day. (So I got burned by the same thing again).

This can be closed. Thanks.

On Thu, May 28, 2015 at 5:40 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> On my machine, your code works fine:
>
> In [1]: import test_mbar
>
> In [2]: test_mbar.test_mbar_computeOverlap()
> /home/kyleb/opt/lib/python2.7/site-packages/scipy/optimize/minpack.py:237: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
>   solution is possible.
>   warnings.warn(msg, RuntimeWarning)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/pymbar/issues/190#issuecomment-106641709>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
No worries, I'm sure everyone has been hit by this 10 times.
