### ISSUE TITLE
Tests are failing on appveyor

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#192]
From the https://github.com/omnia-md/conda-recipes repo:

https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.80/job/jmpmtykan53cc1ja#L491

**Comment by kyleabeauchamp** [comment]
OK, this is because I'm using the HOME environment variable for locating the optional pymbar datasets files.  There's probably a workaround if we want to support windows.

**Comment by kyleabeauchamp** [comment]
I imagine that the MSMBuilder datasets stuff would encounter the same issue, so presumably we can copy paste whatever solution that have there.

**Comment by jchodera** [comment]
Can you be a bit more specific about which part of MSMBuilder or its tests would retrieve optional datasets to test?

**Comment by kyleabeauchamp** [comment]
I'm not sure how well the MSMB code behaves on windows, actually.  It's here: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/example_datasets/base.py#L45

It's basically a matter of handling an exception and looking in an appropriate place on windows.

**Comment by rmcgibbo** [comment]
Why wouldn't that work just fine on windows? https://docs.python.org/3/library/os.path.html#os.path.expanduser

**Comment by rmcgibbo** [comment]
(i.e., use os.path.expanduser('~') instead of os.environ['HOME'])

**Comment by kyleabeauchamp** [comment]
Cool.  Sounds like we should just backport that function from MSMB.

**Comment by jchodera** [comment]
Want me to do this?

**Comment by kyleabeauchamp** [comment]
From an earlier email conversation, I think @Lnaden was volunteered by @mrshirts.  However, @Lnaden would likely not complain if you did it.

**Comment by jchodera** [comment]
OK, I think I've got it fixed.  I'll add appveyor testing to be sure.

**Comment by jchodera** [comment]
This is all fixed now, and appveyor tests are working.

Should we cut a new release and update the (currently failing) pymbar recipe in https://github.com/omnia-md/conda-recipes ?

**Comment by kyleabeauchamp** [comment]
Sure, might be good to see if we can get windows builds online.

**Comment by davidlmobley** [comment]
Re Windows - just one vote for yes. From a teaching perspective it is very helpful to have things working in Windows. About half of my class this spring had Windows and fortunately everything we needed worked.



—
