### ISSUE TITLE
Where did pymbar-2 binstar packages go?

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#200]
Did someone delete the `pymbar 2` binstar packages?
https://binstar.org/omnia/pymbar/files

**Comment by kyleabeauchamp** [comment]
Not me, maybe there was a jenkins /travis issue

**Comment by jchodera** [comment]
That's my guess as well.

I think it's best to keep both `pymbar2` and `pymbar3` recipes:
https://github.com/omnia-md/conda-recipes/pull/244

Trying to figure out what is going on with travis-ci there...
