### ISSUE TITLE
Problem with the Curve-Fitting-Method-based consistency inspector 

### ISSUE THREAD

**Issue by julianzachmann** [choderalab/pymbar#209]
Hello everybody,

I am running pymbar 3.0 with the alchemical_analysis by David Mobley without problems except for the " -c " flag. 

On the provided sample input data it is running fine but if I want to use it on my dhdl files I get the following mistake: 

Plotting the CFM figure...
/opt/soft/anaconda-2.2.0/lib/python2.7/site-packages/matplotlib/axes/_base.py:2562: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=17.7338848684, right=17.7338848684
  'left=%s, right=%s') % (left, right))
/opt/soft/anaconda-2.2.0/lib/python2.7/site-packages/matplotlib/axes/_base.py:2562: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=17.7624749232, right=17.7624749232
  'left=%s, right=%s') % (left, right))

The strange thing for me is that I don't see any differences between "my_dhdl.xvg" and the sample.xvg and also that all the other options are working without any problem. In case this is of interest: The dhdl-files were generated with Gromacs 5.0.4

https://drive.google.com/folderview?id=0B2M9aqeJrxnYYTlsdU9jMnBQOGs&usp=sharing

Best regards,
Julian

**Comment by FEPanalysis** [comment]
Julian,

Can you please attach all 20 lambda files.
If possible, truncate them to 50.0 ps.

**Comment by mrshirts** [comment]
Thanks for bringing up the issue, and Pavel, thanks for jumping on.  This issue should probably be posted directly at:

https://github.com/MobleyLab/alchemical-analysis

**Comment by julianzachmann** [comment]
I now posted it in "alchemical-analysis".
