### ISSUE TITLE
harmless warning but maybe not user friendly

### ISSUE THREAD

**Issue by halx** [choderalab/pymbar#212]
I occasionally get the following warning.

/usr/lib/python2.7/dist-packages/scipy/optimize/minpack.py:237: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)

I assume this is harmless but may confuse the user.  Can you handle this in pymbar?

**Comment by ppxasjsm** [comment]
I observe the same thing.

**Comment by mrshirts** [comment]
This is something that gets passed up by the optimizer, but we should be able to catch it and provide a friendlier explanation.  Lower priority, but definitely a todo.   Is it occurring with any of the examples?

**Comment by jchodera** [comment]
@mrshirts: Did we ever end up with quantitative assessment of the advantages of this approach from @kyleabeauchamp?

In the absence of such data, and if a paper on this scheme is not forthcoming, I really think we should ditch the `scipy` optimizer and go back to the adaptive method.

**Comment by mrshirts** [comment]
Great question, John.  The approach seemed to be much faster for larger systems. However, I don't know for sure about the robustness.  I will elevate on my todo lists going over the tests and examples again.  Levi will be setting apart a small amount of time to help in this testing.

**Comment by Lnaden** [comment]
This is the same issue from #198 which I tried to address in #202 by detecting the warning and provide a more helpful feedback. That PR fails a build due to time out since it also adds a test to ensure that MBAR solves to the correct solution independent of `SciPy` solver, which takes more time than `appveyor` will allow. I could take another pass at this and see if I can cut the time down by removing some tests.

**Comment by Lnaden** [comment]
We merged #202 to address this. Let us know if this helps clear up the warning for you!

**Comment by halx** [comment]
I haven't seen this warning for a while.  I suggest I reopen should I see the warning again.
