### ISSUE TITLE
Error in direct installation of pybar

### ISSUE THREAD

**Issue by nicholusbhattacharjee** [choderalab/pymbar#214]
Hello,

I am trying to install pybar directly from the source directory.

~/softwares/pymbar-master$ python setup.py install

I am getting the following error.

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Traceback (most recent call last):
  File "setup.py", line 141, in <module>
    main()
  File "setup.py", line 137, in main
    setupKeywords = buildKeywordDictionary()
  File "setup.py", line 111, in buildKeywordDictionary
    setupKeywords["ext_modules"]       = [CMBAR] if six.PY2 else []
AttributeError: 'module' object has no attribute 'PY2'

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Can you kindly help me. I have installed all the utilities i.e.

```
Python 2.7 or later
NumPy
SciPy
NumExpr
six
nose
```

Thanks for the help. #

**Comment by Lnaden** [comment]
It looks like `six` install may be out of date. Can you try updating `six` and trying the install again?

`pip install --upgrade six`

or if you use `conda`:
`conda update six`

**Comment by nicholusbhattacharjee** [comment]
Thank you for the help. The installation is complete. I am trying to run an example. Since I am planing to use it for my REMD results I ran the job in parallel-tempering-2dpmf folder. However it is giving the following error

parallel-tempering-2dpmf$ python parallel-tempering-2dpmf.py

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Traceback (most recent call last):
  File "parallel-tempering-2dpmf.py", line 282, in <module>
    mbar = pymbar.MBAR(u_kln, N_k, verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/pymbar-3.0.0.dev0-py2.7-linux-x86_64.egg/pymbar/mbar.py", line 264, in __init__
    self.f_k = mbar_solvers.solve_mbar_with_subsampling(self.u_kn, self.N_k, self.f_k, solver_protocol, subsampling_protocol, subsampling, x_kindices=self.x_kindices)
  File "/usr/local/lib/python2.7/dist-packages/pymbar-3.0.0.dev0-py2.7-linux-x86_64.egg/pymbar/mbar_solvers.py", line 480, in solve_mbar_with_subsampling
    u_kn_subsampled, N_k_subsampled = subsample_data(u_kn[states_with_samples], N_k[states_with_samples], s_n, subsampling=subsampling)
  File "/usr/local/lib/python2.7/dist-packages/pymbar-3.0.0.dev0-py2.7-linux-x86_64.egg/pymbar/mbar_solvers.py", line 430, in subsample_data
    samples = np.random.choice(np.where(s_n == k)[0], size=(N_k[k].astype(int)), replace=replace)
AttributeError: 'module' object has no attribute 'choice'

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Can you please help me solving the problem. Do I need to put any environment in my .bashrc file for pybar.

**Comment by Lnaden** [comment]
It looks like this is another module version issue. the `numpy.random.choice` function was added in `numpy` 1.7.0 so it might be that numpy is also out of date considering that `six` was out of date too. Try updating your `numpy` version and see if that resolves the problem. It may be worth updating the other pymbar dependencies as well just to be safe.

**Comment by nicholusbhattacharjee** [comment]
Hello again,

Initially I was running it into  Ubuntu 12.04 machine. While shifting to Ubuntu 15.04 the program is running well. But there is a warning message in between the output as provided below

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
/usr/lib/python2.7/dist-packages/scipy/optimize/minpack.py:237: RuntimeWarning: xtol=0.000000 is too small, no further improvement in the approximate
  solution is possible.
  warnings.warn(msg, RuntimeWarning)
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Is this a serious issue. If yes how do I cure it. Thanks for the help.

**Comment by Lnaden** [comment]
That's a warning we have ween from several people now in #198 and #212. I have issued a PR to more gracefully catch that error with #202 and ensure that `SciPys` solver returns a properly normalized MBAR weight matrix. I have personally found that the error is mostly harmless and my own results have been accurate, but you should still verify your results.

**Comment by Lnaden** [comment]
We merged #202 to address this. Let us know if this helps clear up the warning for you!

**Comment by Lnaden** [comment]
Closing this issue. Can re-open if still a problem
