### ISSUE TITLE
Ready for official 3.0 release?

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#215]
@mrshirts @Lnaden @kyleabeauchamp @davidlmobley: Are we OK with cutting an official 3.0 release, updating the conda package, and uploading a new version to `pip`?

**Comment by jchodera** [comment]
I can do this if everyone gives the OK.

**Comment by Lnaden** [comment]
I'd like to see if #202 can be merged so the current `SciPy` solvers have a formal test and its warnings are handled a bit more gracefully. I'm okay with a 3.0 release either way though.

**Comment by mrshirts** [comment]
Hi, all-

Let me take a look at Levi's PR over the next day or so, and then let's
release 3.0.

**Comment by jchodera** [comment]
Sounds good!  I can take a look over the weekend too.

Thanks, @Lnaden!
