### ISSUE TITLE
importing six.zip_longest

### ISSUE THREAD

**Issue by ttfoley** [choderalab/pymbar#216]
Hi all,

I don't know if this counts as an issue, but this seems to be the most appropriate place to put it.

I had some trouble with six on my cluster and found a work around that might be useful for other.s  I don't have permission to use easy_install or anything so I had to find a workaround (just copying pymbar folder over). 

Note: in the lines below, the first import statement gives a name error.

I replaced, in utils.py
from six.moves import zip_longest 
with
from itertools import izip_longest as zip_longest

I would be happy to provide any more info if needed.

Tommy

**Comment by mrshirts** [comment]
No relevant anymore.
