### ISSUE TITLE
computeMultipleExpectations crash

### ISSUE THREAD

**Issue by wjg3** [choderalab/pymbar#221]
computeMultipleExpectations crashes with mismatched array sizes. This is due to a typo in
[https://github.com/choderalab/pymbar/blob/master/pymbar/mbar.py#L1007](https://github.com/choderalab/pymbar/blob/master/pymbar/mbar.py#L1007)

should be `diag = np.ones(2*I,dtype=np.float64)`

Cheers,
Will

**Comment by Lnaden** [comment]
Fixed by #222

Thanks, @wjg3
