### ISSUE TITLE
Issue with numexpr() on MBAR initialization; utils.py expects to find mkl acceleration and crashes when not found 

### ISSUE THREAD

**Issue by bmanubay** [choderalab/pymbar#229]
Howdy folks,

Upon initializing MBAR using:

`# Initialize MBAR with Newton-Raphson`
        `if (n==0):  # only print this information the first time`
                `print ""`
                `print "Initializing MBAR:"`
                `print "--K = number of Temperatures with data = %d" % (originalK)`
                `print "--L = number of total Temperatures = %d" % (K)`
                `print "--N = number of Energies per Temperature = %d" % (numpy.max(Nall_k))`

        # Use Adaptive Method (Both Newton-Raphson and Self-Consistent, testing which is better)
        if (n==0):
                initial_f_k = None # start from zero
        else:
                initial_f_k = mbar.f_k # start from the previous final free energies to speed convergence

        mbar = pymbar.MBAR(u_kln, Nall_k, verbose=False, relative_tolerance=1e-12, initial_f_k=initial_f_k)`

^^(Sorry for how this block of code looks. I couldn't get it to look right in github. I assure you it is structurally correct in the actual python script)

I get an issue with the numexpr module trying to find a means for mkl acceleration, which gave the following error stack upon failing to do so.

`pythonpython: : symbol lookup errorsymbol lookup error: pythonpython: /home/bmanubay/anaconda2/lib/python2.7/site-packages/numexpr/../../../libmkl_vml_avx2.so: : /home/bmanubay/anaconda2/lib/python2.7/site-packages/numexpr/../../../libmkl_vml_avx2.so: symbol lookup errorsymbol lookup errorpython: undefined symbol: mkl_serv_getenv: : : undefined symbol: mkl_serv_getenv/home/bmanubay/anaconda2/lib/python2.7/site-packages/numexpr/../../../libmkl_vml_avx2.sopython/home/bmanubay/anaconda2/lib/python2.7/site-packages/numexpr/../../../libmkl_vml_avx2.sopythonsymbol lookup error: python: : : :
undefined symbol: mkl_serv_getenv: symbol lookup errorundefined symbol: mkl_serv_getenv`

(very odd traceback...)

From what @mrshirts and I could tell, the origin is traced back to utils.py where the `logsumexp()` function calls `numexpr.evaluate()` on multiple occasions. We checked that numexpr() was functional on my python installation, but we think MBAR might be trying to implement some mkl option automatically without testing for it first. Any thoughts?

**Comment by Lnaden** [comment]
That looks like its more of a conda MKL error than pymbar as it appears in the [more general GitHub issue](https://github.com/conda/conda/issues/2031).

Have you updated the MKL install?

**Comment by bmanubay** [comment]
Let me check on that.

**Comment by bmanubay** [comment]
That does fix that issue (derp :p). Thanks! Michael and I were discussing whether that mkl dependency could be added as an option in the pymbar code, but it seems like that's really farther down in the numexpr initialization, huh?

**Comment by Lnaden** [comment]
Right. `utils.py` tries to load `numexpr` which is part of the MKL acceleration library, and has a fallback if it can't find it. So the issue would lie at that level.

**Comment by davidlmobley** [comment]
I just ran into this same issue. It would be nice if there were some way to make this play more nicely with respect to conda. I had to use Google to figure out I should conda install the `mkl-rt` module, which is peculiar since normally conda handles the dependencies without issue. Could it be fixed by perhaps making `pymbar` need at least a certain release of `mlk-rt`?

**Comment by mrshirts** [comment]
The current plan is to revert some of the algorithms back to not need mlk-rt.  I just got back from travelling, and this is one of the things to do in the next couple weeks.  Thanks for the feedback!
