### ISSUE TITLE
Document nose test requirements and procedure

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/pymbar#244]
It wasn't totally clear to me how to get all of the nose tests to work. I did:

    nosetests2 ./pymbar

in the top level of the git repo and that seemed to work. However, I had to also install `pytables` and `statsmodels` as well as download the pymbar-datasets repo (see #243).

**Comment by jchodera** [comment]
We actually just updated the readthedocs documentation to describe basic testing, but somehow that didn't get pushed. I'm not sure why. Checking...

**Comment by jchodera** [comment]
OK, it seems to be working now, though I have to do some formatting cleanup: 

http://pymbar.readthedocs.io/en/master/getting_started.html

I'll add a note about using `pytables` and `statsmodels` for testing.

**Comment by wesbarnett** [comment]
Thanks for fixing everything. I am interested in the testing part since I have some build scripts for my system where I like to automate the build and testing before installation. The are actually available for any Arch Linux users in their community-contributed repository.

**Comment by jchodera** [comment]
It looks like we'll have to get things sorted out over the next few weeks as we figure out what shape things are currently in and how to move forward. Sorry for the disorganization---the person that was maintaining this repo for us abandoned it in a very fragmented state, and we're only now picking up the pieces.
