### ISSUE TITLE
[nosetests] RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/pymbar#245]
It seems like the test passed but with a warning:

    compare detectEquilibration implementations (with and without binary search + fft) ... /usr/lib/python2.7/site-packages/statsmodels/tsa/stattools.py:424: RuntimeWarning: invalid value encountered in divide
      acf /= acf[0]
    ok

**Comment by jchodera** [comment]
I'm not sure who added [this test](https://github.com/choderalab/pymbar/blob/master/pymbar/tests/test_timeseries.py#L108-L128), but it appears to be defective. There is no way these methods can produce reasonable output when the only data that is included in a timeseries span is constant.

**Comment by jchodera** [comment]
It looks like @smcantab added this test: https://github.com/choderalab/pymbar/commit/360f1a5243ab7f654752811b87e955471e5bfa61

I've added a fix in #248 by removing the constant region of the test timeseries.

**Comment by smcantab** [comment]
I can't remember if I added the flat segment to the time-series trying to
trigger an exception for which I contributed a bug fix or whether I did it
because it's just common for the time-series to be flat at the end (when
the mc acceptance rate is low). I think it's the first one though. A
time-series from a monte carlo run is always going to be a succession of
flat regions (unless one subsamples beforehand).

**Comment by jchodera** [comment]
>  A time-series from a monte carlo run is always going to be a succession of flat regions (unless one subsamples beforehand).

True, but the region of the timeseries being analyzed *must* have nonzero variance in order for any of these statistical methods to work. If we did want to include real (or artificial) Monte Carlo data, it *must* both mimic the real statistical properties of a Monte Carlo timeseries and we *must* exclude it from analyzing only-constant regions---it has to include much more data than that.

**Comment by jchodera** [comment]
That said, we still appreciate the contributed test!

**Comment by smcantab** [comment]
ok so a quick idea is to replace "if (end - start < 4): break" with (end-start)
// bs_nodes < len_smallest_constanst_subarray, and probably it should be
moved before the for loop. In fact that 4 should have been at least
bs_nodes.

**Comment by smcantab** [comment]
sorry i meant len_largest_constant_subarray

**Comment by jchodera** [comment]
A more general solution is to probably do a quick check of every subseries examined to make sure it's not constant. If it *is* constant, we don't consider it as a possible time origin. If all subseries are constant, we throw an exception that there's nothing we can do.

I'll create an issue for this. Thanks!
