### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#246]
We're planning to release 3.0.0 on Fri 6 Jan.

After that, we should evaluate who should become the primary maintainer of `pymbar`.

If it falls to me, my plan is to do a complete reversion back to `pymbar 2.x` solvers (focusing on the adaptive hybrid method for solving the MBAR self-consistent equations) and release pymbar 4.0.0 as soon as possible.

**Comment by mrshirts** [comment]
Let's talk with Naden/Shirts/Chodera (and others who might want to be involved) soon after the 6th to decide.

**Comment by Lnaden** [comment]
3.0 has been out for a while
