### ISSUE TITLE
Overhaul compiled C extensions

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#253]
We need to ditch the old, broken, py 3.x-incompatible `_pymbar.c` compiled extension and use something more portable and compatible.

For now, it is disabled.

cc: #251 

cc: https://github.com/alchemistry/alchemlyb/pull/5

**Comment by mrshirts** [comment]
Suggestions for different extensions, or even needed now?

**Comment by Lnaden** [comment]
We could probably replace it with Cython code, but if its routines are all handled by numpy code, then I doubt the Cython code would make it faster

**Comment by mrshirts** [comment]
Right now, just looking at the code, everything depends on the speed of logsumexp (in numexpr).  If that is properly accelerated, there's likely not that much more that could be done.  I will do some more fine-grained performance testing later.

**Comment by mrshirts** [comment]
We will be accelerating with other means.
