### ISSUE TITLE
Request for making pymbar pip installable

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#257]
Mentioned here.

https://github.com/alchemistry/alchemlyb/issues/4#issuecomment-278512921

**Comment by dotsdl** [comment]
Should be fine, apologies for the noise. That issue was old, and [`pymbar` 3.0 is `pip` installable from PyPI](https://github.com/alchemistry/alchemlyb/pull/5#issuecomment-269866181) at the moment.

**Comment by dotsdl** [comment]
You can probably safely close this.
