### ISSUE TITLE
Cut a 3.0.1 release for Numpy Fixes

### ISSUE THREAD

**Issue by Lnaden** [choderalab/pymbar#260]
I want to cut a 3.0.1 release to make sure `pymbar` is NumPy 1.12 and Python 3.6 capable. Are there any objections to this?

With the `omnia` conda channel supporting the new version of Numpy and Python 3.6, we should make sure that there is a formal release to support these package versions. However, there are a few dependencies that are not Python 3.6 ready yet (I'll curate them in a later post) that we will need to keep an eye on first.

**Comment by Lnaden** [comment]
Missing packages:
* `nose-timer` (OSX, py36)

**Comment by Lnaden** [comment]
I have cut the release for this and uploaded to the omnia channel.

@jchodera the builds appear to be going to the `dev` tag instead of the `main` tag. Is that because [I have the `beta` tag on the revision?](https://anaconda.org/omnia/pymbar/files?page=1)

**Comment by jchodera** [comment]
Yes re beta in the version number---that is causing the dev channel to be used.

**Comment by Lnaden** [comment]
Okay, is it the `meta.yaml` file on the `conda-recipes` file that I need to change, or the actual version on the git tag?

Secondly, do we need to publish a version for every numpy with the `numpy x.x` in the yaml file, or can we just set `numpy` in the file and let it just build against python version only?

**Comment by jchodera** [comment]
Only the `meta.yaml` is used to identify which channel this is uploaded to, but it's a good idea to keep this consistent with the git revision. 

In this case, moving the packages from `dev` to `main` on the anaconda cloud web UI may be the easiest fix.

> Secondly, do we need to publish a version for every numpy with the numpy x.x in the yaml file, or can we just set numpy in the file and let it just build against python version only?

I'm afraid I'm not sure of the answer to this.

**Comment by Lnaden** [comment]
> moving the packages from dev to main on the anaconda cloud web UI may be the easiest fix.

Do you have permission to do this? It would need to be all of the 3.0.1.beta0 files.

> I'm afraid I'm not sure of the answer to this.

If you are not sure then I don't actually think we do. Most of the NumPy related fixes I have put in since 3.0.0.beta2 were explicitly to use the newer version of NumPy code (and some code that will just flat break on 1.12) and to remove as many of the `FutureWarning` and `DepricationWarning`s as I could

**Comment by jchodera** [comment]
> Do you have permission to do this? 

I've just made you an owner of the `omnia` org.

> It would need to be all of the 3.0.1.beta0 files.

It's easy to do by checking all the packages and then using the "Set label" drop-down.

https://anaconda.org/omnia/pymbar/files

**Comment by Lnaden** [comment]
Done and done, woo! Thanks
