### ISSUE TITLE
Question about "usage example"

### ISSUE THREAD

**Issue by mcchran** [choderalab/pymbar#265]
Hello, guys

I am actually quite new in the field of MD. However while running the "usage example", as it is referred on your main page, I get dDeltaf_ij values significantly larger than Deltaf_ij values. Is this because of the small-sized input dataset, or am I missing something?

Best,
C.

**Comment by mrshirts** [comment]
Nothing _inherently_ wrong with dDeltaf_ij values being larger than Deltaf_ij; of the dDeltaf_ij's are supposed to be zero, for example, then the uncertainties could easily be larger than the values themselves.  I could get into more detail if you posted what the output was -- otherwise, my answer will be mostly guesswork!

**Comment by mcchran** [comment]
I just experimented with the following commands:
`from pymbar import testsystems
from pymbar import MBAR
[x_n, u_kn, N_k, s_n] = testsystems.HarmonicOscillatorsTestCase().sample()
 mbar = MBAR(u_kn, N_k)
(Deltaf_ij, dDeltaf_ij, Theta_ij) = mbar.getFreeEnergyDifferences()`

The output was:
Deltaf_ij
array([[ 0.        ,  0.31924375,  0.57871447,  0.58739889,  1.1832112 ],
       [-0.31924375,  0.        ,  0.25947071,  0.26815514,  0.86396745],
       [-0.57871447, -0.25947071,  0.        ,  0.00868442,  0.60449674],
       [-0.58739889, -0.26815514, -0.00868442,  0.        ,  0.59581231],
       [-1.1832112 , -0.86396745, -0.60449674, -0.59581231,  0.        ]])

dDeltaf_ij
array([[ 0.        ,  0.23708541,  0.39211748,  0.5499802 ,  0.76674411],
       [ 0.23708541,  0.        ,  0.23527757,  0.4523484 ,  0.70018824],
       [ 0.39211748,  0.23527757,  0.        ,  0.32843007,  0.62743565],
       [ 0.5499802 ,  0.4523484 ,  0.32843007,  0.        ,  0.49426232],
       [ 0.76674411,  0.70018824,  0.62743565,  0.49426232,  0.        ]])

I am not quite sure what are the output but I have the intuition that Deltaf_ij >> dDeltaf_ij.
Any further explanation should be quite welcome!

**Comment by mrshirts** [comment]
It would depend on the numbers of samples.  try increasing N_k for the different states and see what happens.
