### ISSUE TITLE
Add nose tests for bar.py

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#288]

**Comment by mrshirts** [comment]
Could do it, though would likely need a bit more orientation about doing it right. Anything different than copying and paring test_mbar.py

**Comment by Lnaden** [comment]
I don't see any reason you could not just copy the test_mbar.py file and put BAR in its place. The calls to BAR are different than MBAR though, so it would take some editing. In theory though, so long as the file name and the function names match `nose`'s regex pattern for what is a "test," it should run with the CI tests

**Comment by mrshirts** [comment]
addressed by #345
