### ISSUE TITLE
Next steps with pymbar/examples?

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#289]
Are pretty useful examples to see what MBAR can do.

I am currently converting them to be python 3 compatible.

Should I turn them into iPython notebooks rather than scripts?  Thoughts?

**Comment by Lnaden** [comment]
Although IPython notebooks would be more interactive, people would still have to download them and run them themselves unless we find a way to host them. They will be tricker to maintain. I think the scripts are fine for now though, once we get them Py3 compatible.

**Comment by mrshirts** [comment]
OK, I'll just do a conversion for now.
