### ISSUE TITLE
Whether or not to remove computePMF from the mbar.py module?

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#298]
I am likely to check in a lot of extra methods for calculating PMF's in the near future.  For this, it might be convenient to separate out the PMF functionality as a separate module to separate out the functionality.

However, the computePMF function requires a fair amount of data from mbar.  For example. it uses data self.N_k, self.K, self.Log_W_nk, and method self._computeAsymptoticCovarianceMatrix.  It might be therefore a little hard to completely separate it out.  So maybe we just add a bunch more functions to mbar.py? Other suggestions for how to organize this?

**Comment by Lnaden** [comment]
A couple ideas off the top of my head:
* Decouple the common functions to `utils.py` or some other helper module
* Split out MBAR and PMF into subclasses of the same abstract parent

**Comment by mrshirts** [comment]
I guess in this case the computePMF uses data stored in the MBAR object, not just using the same functions, so one can pass either that MBAR object, or just pass the data from that object. . . (I think should work). 

self._computeAsymptoticCovarianceMatrix does not use any data in MBAR, so that could be move to a utility module.

**Comment by mrshirts** [comment]
Added an initial implementation in #309

**Comment by mrshirts** [comment]
Addressed by #327
