### ISSUE TITLE
PendingDeprecationWarnings with latest numpy?

### ISSUE THREAD

**Issue by rmcgibbo** [choderalab/pymbar#305]
When running some of my tests with python-3.7 / numpy-1.15.1, I saw a large number of `PendingDeprecationWarning` being thrown by `mbar.py`.

I don't think any urgent changes are necessary, but I wasn't sure whether or not this was on your radar yet. 

The message is:
```
PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
```

**Comment by Lnaden** [comment]
NumPy 1.5.1 or did you mean Numpy 1.15.1?

**Comment by Lnaden** [comment]
Ah okay, I was very confused for a minute. 

I was unaware that was a new thing. I'll look into resolving that.

**Comment by mrshirts** [comment]
Interesting.  There were a number of things we couldn't do with ndarray before (2.6 or so), like take transposes and get a nxm array change to a mxn array.  Maybe numpy has changed it. 

I'm happy to help taking a look at this.

**Comment by rmcgibbo** [comment]
I'm not sure what the best reference is for the reasons for its deprecation, but this message from one of the core maintainers on the mailing list is something:

```
I can't imagine we'll actually remove 'matrix' from the numpy 
namespace at any point in the near future. 

I do have the sense that when people choose to use it, they eventually 
come to regret this choice. It's a bit buggy and has confusing 
behaviours, and due to limitations of numpy's subclassing model, will 
probably always be buggy and have confusing behaviours. And it's 
marketed as being for new users, who are exactly the kind of users who 
aren't sophisticated enough to recognize these dangers. 

Maybe there should be a big warning to this effect in the np.matrix docstring? 

Maybe using np.matrix should raise a DeprecationWarning? 
(DeprecationWarning doesn't have to mean that something will be 
disappearing -- e.g. the Python stdlib deprecates stuff all the time, 
but never actually removes it. It's just a warning flag that there are 
better options available.) 

Or what?
```
(ref: http://numpy-discussion.10968.n7.nabble.com/deprecate-numpy-matrix-td36282.html)

array now has methods/accessors like `.dot`, `.T`, so it's pretty convenient for linear algebra. (and `@`, once you're lucky enough to drop python2).

**Comment by mrshirts** [comment]
#334 is now addressing this, so closing.
