### ISSUE TITLE
Questions about embedded C++ optimizations in pyMBAR

### ISSUE THREAD

**Issue by Leepengfei** [choderalab/pymbar#306]
Dear all,

Recently, I calculated the PMF (potential of mean force) by pyMBAR software.
Here, pymbar-2.0beta version is used by us.
When I deal with 493,000 data points (493 windows * 1000 data points per window), I can get a correct PMF as I expect.
Two key points in calculations of PMF using pyMBAR are displayed as follows:
![image](https://user-images.githubusercontent.com/9461715/47506413-8efc4880-d8a2-11e8-83ce-0b726f8fc03a.png)
![image](https://user-images.githubusercontent.com/9461715/47506429-9885b080-d8a2-11e8-9d37-ceef654e7d26.png)
But, when I deal with 986,000 data points (493 windows * 2000 data points per window), I can’t get a PMF result. 

Then, I try to find out why it happened. I find that there are wrong iterations during the calculations of free energies f_k for the thermodynamic states are done. Until the end of iterations, the PMF calculation failed, due to wrong f_k values. The error information is displayed:
![image](https://user-images.githubusercontent.com/9461715/47506449-a89d9000-d8a2-11e8-98fd-abd26f0d0528.png)
Then, I try to use self-consistent-iteration method instead of the adaptive iteration method, but it still doesn’t work. Later then, I try to use pure python code instead of using embedded C++ optimizations in function (def _computeUnnormalizedLogWeights(self, u_kn)), then it works. 

Thus, I think that there may be something wrong in embedded C++ optimizations code while dealing with a large amount of data points.

Looking forward to getting your help.

Best wishes,

Pengfei Li

**Comment by mrshirts** [comment]
Thanks for the bug report. I will try testing with harmonic oscillators with that number of data points and see if I can replicate a problem.

Could you see if the problem is present in pymbar 3.0?  That uses numpy as a default, and might not have this problem.

**Comment by Leepengfei** [comment]
@mrshirts Dear Prof. Shirts, Thanks for your help. Sure, I will try it using pymbar 3.0. Once results appear, I will post here. By the way, the explanation of MBAR from the view of mixture distribution you gave last year is very helpful for us to understand MBAR. In my opinion, it is very great. And thank you for sharing!

**Comment by Leepengfei** [comment]
@mrshirts Hi Prof. Shirts, I have tested the pymbar 3.0 with the same data. Indeed, it doesn't have this problem and the correct results can be obtained. And it can be found that version 3.0 is more efficient than version 2.0-beta. Thanks for your help again. Pengfei Li, East China Normal University.

**Comment by mrshirts** [comment]
Excellent.  We have been moving away from any further development of 2.0-beta.  Glad 3.0 is working for you.
