### ISSUE TITLE
Installing `pymbar` from conda forcing a downgrade of Python 3.7 → 3.6

### ISSUE THREAD

**Issue by slochower** [choderalab/pymbar#311]
Installing `pymbar` from `omnia` via `conda` is trying to downgrade python (and a bunch of other packages). I'm not sure this is the intended effect (I can't see anything in the repository pinning `python=3.6` or `python<3.7`). 

Briefly, I had an environment with `pymbar` installed, upgraded `ambertools` from 18 to 19 and `python` from 3.6.x to 3.7.3. I then lost the ability to `import pymbar`. I thought this was probably removed accidentally during whatever magic `conda` uses for conflict management, but trying to reinstall `pymbar` using the same command will downgrade ~20 packages, including python. 

```
(paprika-dev) /m/d/d/p/pAPRika-dev ❯❯❯ conda install -c omnia pymbar                                             ✘ 2 openmm-2
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/davids4/data/anaconda3/envs/paprika-dev

  added / updated specs:
    - pymbar


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    coverage-4.3.4             |           py36_0         226 KB  omnia
    ------------------------------------------------------------
                                           Total:         226 KB

The following NEW packages will be INSTALLED:

  pymbar             omnia/linux-64::pymbar-3.0.1.beta0-np111py36_0


[snip]
The following packages will be DOWNGRADED:
[snip]
  python                                   3.7.3-h0371630_0 --> 3.6.8-h0371630_0
```

**Comment by mrshirts** [comment]
I wonder if @Lnaden would be able to come in quickly and update the installation manager?  I think there are error warnings that are due to bad configurations (as see  with https://github.com/choderalab/pymbar/pull/309) that need to be addressed.

**Comment by Lnaden** [comment]
You'll want to get `pymbar` from the `conda-forge` channel rather than the `omnia` channel. 

We moved the `pymbar` deployment from `omnia` to c-f a while ago, but we left the older packages on omnia available for reproducibility. We also recommend that any time you specify the `omnia` channel, you also specify `conda-forge` as an additional, higher-priority channel to ensure the dependencies resolve correctly.

Changing the channel should get you up and going.

**Comment by slochower** [comment]
Hm, thanks. `conda install -c conda-forge -c omnia pymbar` does work as expected. In the file that I used to create the environment, there are both `omnia` and `conda-forge` packages. I guess the issue comes when upgrading single packages down the line: e.g., manually upgrading AmberTools from 18 to 19 to test in my development environment kicked out `pymbar` and my one-liner was trying to pull in things *only* from conda-forge.

**Comment by Lnaden** [comment]
Right. If you use another `conda install` or similar command with different `-c ...` settings, it resolves *only* for that command and makes changes to the environment to solve that *specific* call. Its why we say for all `omnia` packages to also include `conda-forge` as a higher priority channel to help reduce those oddities. If you are having issues with resolution, try doing everything in 1 line carefully considering the channel priority.

**Comment by Lnaden** [comment]
@slochower can we close this issue?

**Comment by slochower** [comment]
Yup
