### ISSUE TITLE
Warning: Should have \sum_n W_nk = 1.

### ISSUE THREAD

**Issue by xadams** [choderalab/pymbar#317]
To test my understanding of pymbar, I was first applying it to the 1-D REUS NAMD tutorial (https://www.ks.uiuc.edu/Training/Tutorials/science/umbrella/REUS-1D.pdf) in place of WHAM to ensure I could replicate the results. After generating simulation data, I ran the attached python script (reus.txt) and received the error: 
"Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 1.433238. 16 other columns have similar problems". 
If I remove the subsampling from my script then the method completes, but the reported PMF is 2 orders of magnitude different from WHAM results, which match the tutorial file. I have attached both outputs as error.txt and no_subsampling.txt. I checked for overlap, shown in the attached histogram plot, and am unsure how best to proceed from here. My thanks in advance,

Alex Adams

[reus.txt](https://github.com/choderalab/pymbar/files/3888155/reus.txt)
[error.txt](https://github.com/choderalab/pymbar/files/3888140/error.txt)
[no_subsampling.txt](https://github.com/choderalab/pymbar/files/3888141/no_subsampling.txt)
![REUS_histograms](https://user-images.githubusercontent.com/23018957/69568670-06127d80-0f8a-11ea-9b84-155ce5286c5c.png)

**Comment by jchodera** [comment]
Thanks for opening an issue! Is it possible to attach a ZIP archive with both your scripts and the input data?

**Comment by xadams** [comment]
Here is everything except the raw output. The collective variable data has already been extracted from the trajectories into the analysis folder.
[reus_example.zip](https://github.com/choderalab/pymbar/files/3888932/reus_example.zip)

**Comment by mrshirts** [comment]
Currently, the parsing is such that it's reading in the temperature as 1 Kelvin, resulting in very large reduced potential energies beta*U.

Also, make sure that you have correct conversion between kJ and kcal, both in the input and the output.

**Comment by jchodera** [comment]
Good catch, @mrshirts! 

Since failures like this almost always indicate a file parsing issue or issue with consistency of thermodynamic states, I wonder if we should add some self-consistency checking that could help detect issues like this and point to likely causes.

**Comment by mrshirts** [comment]
We should add some checks when we can.  In this case, it's hard to know that the temperature wasn't supposed to be 1 K, but should be 300 K.   Maybe it's just a matter of adding some text of what to look for.   "Warning: Should have \sum_n W_nk = 1. This indicates that there is not phase space overlap in the sampled configurations from different states. Check that your  data is being read in correctly from the file, that the temperatures are correct," etc.

**Comment by xadams** [comment]
Correcting the parsing issue converged the script and properly converting units brought the output in line with the expected results. Thank you immensely for the help and insight into troubleshooting.
