### ISSUE TITLE
Publish release 3.0.5 to PyPI

### ISSUE THREAD

**Issue by dotsdl** [choderalab/pymbar#321]
The critical bugfix release 3.0.5 [has been generated](https://github.com/choderalab/pymbar/releases/tag/3.0.5). However, it does not yet appear to be published on PyPI. This release restores the previous API of returned structures.

**Comment by dotsdl** [comment]
@jchodera, @Lnaden, and @mrshirts, I believe this is something only one of you can do. Thank you for continuing to advance this package!

**Comment by jchodera** [comment]
I think I've managed to do this correctly:
https://pypi.org/project/pymbar/3.0.5/#history
Please reopen if you have more trouble!

**Comment by dotsdl** [comment]
Cool, thank you!
