### ISSUE TITLE
Address collections warning in testing?

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#351]
Tests are generating following warning. Collections isn't in the code as far as I can tel.  Is the conda package that the testing runs just out of date?  What else would need to be addressed to fix?

/usr/share/miniconda/envs/test/lib/python3.8/site-packages/patsy/constraint.py:13
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping

-- Docs: https://docs.pytest.org/en/latest/warnings.html

----------- coverage: platform linux, python 3.8.1-final-0 -----------
Coverage XML written to file coverage.xml

**Comment by Lnaden** [comment]
That is an upstream package `patsty` which is installed by `statsmodels` throwing that warning. Not much we can do about it directly since its on the `patsy` devs to fix it. I can look into suppressing warnings from other packages we don't use directly since I dont know if/when they will update it.

**Comment by mrshirts** [comment]
I guess mark this as `won't fix` for now?

**Comment by jaimergp** [comment]
`patsy` got this addressed in https://github.com/pydata/patsy/pull/140#issuecomment-433760027, but they haven't cut a release yet. Issue asking for that is here: https://github.com/pydata/patsy/issues/154. They are specifically asking for the release to remove the `collections` warning.  Let's see if we can add some pressure there :)

**Comment by jaimergp** [comment]
We _could_ (I am not saying this is a good idea) manually upgrade `patsy` to the `master` release to remove the warnings in our CI if this is really annoying us.

**Comment by Lnaden** [comment]
This will be fixed (at least suppressed) in #357, we can undo it later.

**Comment by Lnaden** [comment]
Fixed by #357
