### ISSUE TITLE
PEP8: how can we avoid breaking API

### ISSUE THREAD

**Issue by jaimergp** [choderalab/pymbar#363]
Parts of the library do not follow PEP8 names.

I took a look at `/examples` and compiled the names there imported:

```
class pymbar.MBAR (+ its methods)
class pymbar.PMF (+ its methods)
class pymbar.utils.DataError
class pymbar.utils.ParameterError
function pymbar.BAR
function pymbar.confidenceintervals.AndersonDarling
function pymbar.confidenceintervals.generateConfidenceIntervals
function pymbar.confidenceintervals.QQPlot
function pymbar.EXP
function pymbar.EXPGauss
function pymbar.timeseries.statisticalInefficiency
function pymbar.timeseries.subsampleCorrelatedData
function pymbar.utils.kn_to_n
```

These should either:

A. left alone for now, or
B. be an alias to the PEP8-compliant name with a DeprecationWarning

We should probably include more names in that list, but the question is the same: how do we want to face these changes?

**Comment by mrshirts** [comment]
So, this is a great questions.  Having existing code break for a data return issue is one thing, where the fix is clear, quick, and 1 line is one thing.  Having all code break because all functions are named to meet a naming convention is another thing.   

What would these names be changed to?  

I'd love to have more input on this before we make such a change.

**Comment by jaimergp** [comment]
`generateConfidenceInterval` would become `generate_confidence_interval`, as recommended by [PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names). They do mention that `camelCase` is acceptable in legacy code, though.

**Comment by jchodera** [comment]
I think we should have pymbar 4 comply with PEP8 even if we break the API. Folks can continue to use the old pymbar by pinning it if they need the old API. We need to move forward, though.

**Comment by mrshirts** [comment]
> They do mention that camelCase is acceptable in legacy code, though.

So technically that is PEP8 compliant?  I sort of want to get some user thoughts.  I can understand the instinct, but I worry about the reality.  Maybe a post on the alchemistry slack channel to get feedback, if we can say what would change to what (what would pymbar.MBAR change to?)

**Comment by jaimergp** [comment]
`pymbar.MBAR` (the class name) would not change, but its methods would. For example `MBAR.computeCovarianceOfSums` would become `MBAR.compute_covariance_of_sums`.

I'll share this issue in Slack so we get user feedback! Thanks for the suggestion!

**Comment by jaimergp** [comment]
Oh, I don't think I have access to that Slack server.

**Comment by jchodera** [comment]
@mrshirts : What is the drawback of breaking the API in pymbar 4? The main concern, as I understand it, is that existing applications won't work. But that's easy to fix by just pinning to pymbar < 4, which works perfectly fine.

The hope for pymbar 4 is to support some advanced hardware and large scale applications that legacy applications do not use pymbar for yet, so there should be no risk in breaking the API.

**Comment by SimonBoothroyd** [comment]
My + 1 would be for cutting a 3.0.6 release whose only change is to implement option B

> B. be an alias to the PEP8-compliant name with a DeprecationWarning

That way users at least get a heads up and a chance to migrate early without breaking things while 4.0 is worked on / finalized.

**Comment by mrshirts** [comment]
That seems like it might be a good path forward.  There are a couple of actual improvements / bug fixes that have been found / we may find over the next couple weeks that we should backport as well.

**Comment by mrshirts** [comment]
Closing this, since the solution is #365
