### ISSUE TITLE
List of what to backport to pymbar3 in preparation for pymbar4 release

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#364]
1. Warning about deprecation of old names so people are aware the change for pymbar4

2. Memory leak fixes (When addressed correctly in #359

**Comment by mrshirts** [comment]
3. Bug fix in BAR caught in #350.

**Comment by jaimergp** [comment]
I think we should also add a warning on the new `pmf.py` module and the `PMF` class, which now address the former `mbar.computePMF`?

**Comment by mrshirts** [comment]
What specific warning?

**Comment by jaimergp** [comment]
In `pymbar v3`, PMF is computed via `mbar.MBAR.computePMF()`. The deprecation warning in this case should redirect to `pmf.PMF(...)`, if I understood correctly?

**Comment by mrshirts** [comment]
We can have such a message: "when you use pymbar4, use pmf.PMF functionality" though the syntax is not quite the same, and it can't be used in pymbar4, which is different from the messages on snake_case, since it's set up so that you can use new syntax immediately.

**Comment by jaimergp** [comment]
> Memory leak fixes (When addressed correctly in #359)

359 got closed, but issue #341 is still open. Will we backport anything to v3 or this is not part of the roadmap?

**Comment by mrshirts** [comment]
Nothing from #341 will be backported to 3.0.

**Comment by jaimergp** [comment]
See #417 for a summary of changes. Closing this one for clarity!
