### ISSUE TITLE
Create PR that deprecates 3.0 names and warns people about the 4.0 names.

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#365]
Create a PR with a deprecation warning for a new 3.0.X release for old names 3.0 names so people are aware the change of names for pymbar4. See the discussion behind this proposal in #363

**Comment by jaimergp** [comment]
Working on this today. I'll merge currently opened PR to a new branch `3.0_branch` (following OpenMM's strategy) to minimize the commit conflicts for v4.

**Comment by jaimergp** [comment]
Addressed in #368
