### ISSUE TITLE
pmf.py reformatting

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#369]
- Fix lint-ci issues.
- Break up the code into fewer functions.

**Comment by jaimergp** [comment]
Adding a link to this comment in the PR so we don't miss it!

https://github.com/choderalab/pymbar/pull/367#issuecomment-594399476

**Comment by mrshirts** [comment]
Addressing this in #385

**Comment by mrshirts** [comment]
Starting to address breaking it up in #385

**Comment by mrshirts** [comment]
Being addressed by #385

**Comment by mrshirts** [comment]
Addressed by #385
