### ISSUE TITLE
MBAR initialization only checks for duplicate states of verbose=True

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#376]
Is that the desired behavior?

**Comment by jaimergp** [comment]
You mean this block [here](https://github.com/choderalab/pymbar/blob/pymbar4/pymbar/mbar.py#L248-L287)?

**Comment by mrshirts** [comment]
Correct - sorry for not pointing it out specific lines, this was more a reminder for me.  Though I guess the results will be right regardless.

**Comment by mrshirts** [comment]
I'll close for now.
