### ISSUE TITLE
Release conda package

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#38]
We should release a conda package, likely putting a recipe here:

https://github.com/omnia-md/conda-recipes

**Comment by kyleabeauchamp** [comment]
Conda packages for 2.1 are available on omnia binstar.

**Comment by jchodera** [comment]
Were these not being built by jenkins?

**Comment by kyleabeauchamp** [comment]
They were made 8 days ago, presumably by jenkins.
