### ISSUE TITLE
Rename PMF functionality to "free energy profile" or "free energy surface" functionality?

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#395]
After some literature searching, I think it might be more accurate to change reference to the functionality that calculates the free energy as a function of a collective coordinate from "potential of mean force" to "free energy surface" or "free energy profile".  

When using umbrella sampling, then one is calculating F(\xi), where \xi is the collective coordinate.  But the potential of mean force depends on the coordinate system that one uses to calculate the forces.  See http://www.nyu.edu/classes/tuckerman/stat.mech/lectures/lecture_11/node3.html.  See the discussion here as well: https://pubs.acs.org/doi/abs/10.1021/ct400134d and https://link.springer.com/article/10.1140/epjst/e2011-01519-7.

The free energy profile is actually what one wants to use if calculating barrier heights along a reaction coordinate anyway (OK, I'm reading more, especially https://link.springer.com/article/10.1140/epjst/e2011-01519-7, and it's not necessarily quite as clear which free energy profile is needed; it may depend on what "dynamics" means).

Regardless, I'm thinking we should probably be more explicit in what the code calculates, with some discussion about the connection between the free energy surface and the potential of mean force in the documentation.  

This will involve a fair amount of renaming and rewriting documentation, though no real change of functionality.  What do people think?

**Comment by jaimergp** [comment]
From the refactor point of view, if there's a moment to do such a renaming it's now. As long as we track every change so we can add `DeprecationWarning`s to the last v3 release, we should be good.

**Comment by mrshirts** [comment]
@jchodera, your thoughts?  As @jaimergp says, the time is now.

**Comment by jchodera** [comment]
I like "free energy profile", and making it clear that it's really a negative log probability density in the coordinate `$\xi$`.

**Comment by mrshirts** [comment]
Addressed by #397
