### ISSUE TITLE
Build for Python for 3.9?

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#420]
I'm getting some comments about building python for 3.9 - that has interfered with building physical-validation for 3.9  - see https://github.com/shirtsgroup/physical_validation/pull/80#issuecomment-742171374

**Comment by jaimergp** [comment]
Pymbar 4 is going to be a `noarch` package, so no need to build for specific versions anymore.

For the last pymbar 3.x we can indeed build for all pythons, but for that we need to cut that release first...

**Comment by mattwthompson** [comment]
It looks like the conda-forge infrastructure took care of this? I see [files](https://anaconda.org/conda-forge/pymbar/files) from the bot's (and humans') activity on the [feedstock](https://github.com/conda-forge/pymbar-feedstock/pull/9).

**Comment by jaimergp** [comment]
Yep, Levi took care of that here: https://github.com/conda-forge/pymbar-feedstock/pull/9

**Comment by mattwthompson** [comment]
Seems like this can be closed 🙂
