### ISSUE TITLE
Remove corrupted lines in xvg files

### ISSUE THREAD

**Issue by hannahbaumann** [choderalab/pymbar#423]
Hi,

when I want to analyze free energy differences while simulations are still running, the last line of the xvg files is often corrupted (not fully written yet) and alchemlyb fails to do the analysis. Alchemical analysis has a feature that repairs those files, so I usually run that first and then run alchemlyb on the repaired xvg files. Is it possible to move that feature into alchemlyb?
https://github.com/MobleyLab/alchemical-analysis/blob/master/alchemical_analysis/utils/corruptxvg.py

**Comment by jchodera** [comment]
Is this meant as an issue for [alchemlyb](https://github.com/alchemistry/alchemlyb)?

**Comment by hannahbaumann** [comment]
Oh yes, sorry, wrong place, will put it there!
