### ISSUE TITLE
Add methods to compute overlap and effective sample sizes for BAR?

### ISSUE THREAD

**Issue by jchodera** [choderalab/pymbar#427]
@mrshirts : What do you think about adding a corresponding `computeOverlap()` method for BAR? This could help users identify when the BAR uncertainty estimate will be unreliable.

**Comment by mrshirts** [comment]
I shouldn't be too tough, since the right way is, I think, to just run it through MBAR with 2 states and write a wrapper around it.

**Comment by jchodera** [comment]
It would also be great to add a method to compute the effective number of samples.

**Comment by mrshirts** [comment]
Again, would just require calling MBAR as well as BAR and adding that information.  THOUGH - actually might be a bit harder, since MBAR wants energies, not energy differences.  Maybe would take some more playing around.

**Comment by jchodera** [comment]
> THOUGH - actually might be a bit harder, since MBAR wants energies, not energy differences.

This is not a problem---we did something similar for the MBAR paper with the double optical trap.

We would just form a `u_kn` matrix where the first `N_f` values of `w_f = u_kn[1,0:N_f] - u_kn[0,0:N_f]` and the second `N_r` values have `w_r = u_kn[0,N_f:(N_f+N_r)] - u_kn[1,N_f:(N_f+N_r)]`. I think this would be
```
u_kn = np.zeros([2, N_f + N_r])
u_kn[1,0:N_f] = w_f
u_kn[0,N_f:(N_f+N_r)] = w_r
```
You can easily check you have it right by computing the free energy difference between the two states 0 and 1 and confirming it reproduces BAR

I may have `k` and `n` swapped, but the fact that this is a bit tricky for others to tackle is another reason to wrap the logic in a convenient method within `BAR`.
