### ISSUE TITLE
pymbar and high or low potential energy values

### ISSUE THREAD

**Issue by gabriela-correa** [choderalab/pymbar#433]
Hi, everyone!

I'm having a problem with my pymbar potential energy input.

I am performing alchemical free energy calculations in LAMMPS. As outputs from the simulations, I have Gaussian potential energy values ​​in each of the 11 lambda state values. The LAMMPS energy output is in the unit (kcal/mol x atoms).
When I am using the energy  in (kcal/mol x atoms) to perform the pymbar calculations, the results are consistent with the sampled values ​​of the potential energy derivative. However, if I divide the potential energy value by the total number of atoms in the system (Nat = 2048), the pymbar doesn't seem to work properly. The reweighting performed is not consistent with the sampled values ​​of the potential energy derivative. The free energy result is not proportional to that obtained in the first case.

Instead of dividing the potential energy value, I multiplied it by a large number (eg. 1000). In this case, the reweighting performed seems to be better. If I multiply by a very large number, there is an error in the Wn array.

In the simulations, the potential energy is a lambda function as follows
U(r, lambda) = f(lambda)*U_gauss(r)
dU/dlambda = df/dlambda*U_gauss(r)
So, I think that multiplying or dividing the value of U_gauss(r) by some constant shouldn't affect the final result of the pymbar method, except for the proportionality with the applied constant. However, the presence of the constant is drastically changing the behavior of the variables obtained by reweighting as well as the free energy.

Could this problem be something related to memory allocation?
Do you think it's a problem with pymbar or my data?

The folder with the code and results:
[free energy example.zip](https://github.com/choderalab/pymbar/files/8505672/free.energy.example.zip)

**Comment by mrshirts** [comment]
Adding a constant from all of the energies should result in the same answers in the end, because energy differences are what matters. 

Dividing by an arbitrary constant c won't give physical results, because that is the same as taking the probability to the 1/c'th power, which doesn't have any physical meaning.

**Comment by gabriela-correa** [comment]
Thanks for the replies, Prof. Chodera and Prof. shirts.
I'm using reduced potential units.
The output of LAMMPS is in [kcal/mol x atoms]. So I'm dividing the potential by RT in [kcal/mol]. But if I also divide the potential by the number of atoms in the system, pymbar doesn't work well. However, when I use the reduced potential in "atom" units, without dividing by the number of atoms, pymbar works fine. For me the last case should work and is the correct one.
Sorry for answering you so late. I had some problems during this period.
Thank you for your attention!
