### ISSUE TITLE
pymbar 3.1 release not available through PyPI

### ISSUE THREAD

**Issue by boegel** [choderalab/pymbar#475]
I've just noticed that the pymbar v3.1 (LTS) release is not available via PyPI, see https://pypi.org/project/pymbar/#history

Is there a particular reason for this, or is it just an oversight?

For me personally it's not a big problem, installed pymbar from the source tarball obtained for the `3.1` tag in GitHub (https://github.com/choderalab/pymbar/releases/tag/3.1) seems to work just fine...

**Comment by Lnaden** [comment]
Thanks for calling attention to this. It was an oversight which i've [resolved](https://pypi.org/project/pymbar/3.1.0/). Release is the version tagged at 3.1.0
