### ISSUE TITLE
readthdocs not building; looks like config issue

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#493]
readthedocs appears to be failing on build; see https://readthedocs.org/projects/pymbar/builds/19784267/ specifically seems to be behind on numpy versions (jax and jaxlib appears to need 1.20, but only 1.19.2 is installed.  I'm not quite expert enough to fix this.

**Comment by mikemhenry** [comment]
Yes! I was poking at this yesterday while wrapping up pymbar 3 & 4 compatibility for openmmtools. Switching to using mamba for building the docs env will speed it up and also fix issues with using pip to create it.

**Comment by mikemhenry** [comment]
I will keep this issue open until I get the lts branch merged in #495

**Comment by mikemhenry** [comment]
https://pymbar.readthedocs.io/en/3.1.1/
https://pymbar.readthedocs.io/en/4.0.1/

Both working now :)
