### ISSUE TITLE
Examples output pdfs are listed in untracked files

### ISSUE THREAD

**Issue by jaclark5** [choderalab/pymbar#536]
After running the examples provided with the package, a series of pdfs are produced that are recognized by git as untracked files.

**Comment by mrshirts** [comment]
We could add them?  Though be more specific which examples?

**Comment by jaclark5** [comment]
Yes, I'm suggesting to add a gitignore for the optional files that are generated when running the examples. I assumed you didn't want to include them, otherwise they would have been present when forking the repository.
