### ISSUE TITLE
List of 3.0 plans

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#76]
The main thing I can think of that we want to have in 3.0:

* Move to supporting a NxK data representation of the input data matrix , not a KxKxN_k representation
* Explore possible optimizations, especially allowing us to get rid of the additional C code.
* More full-featured docs in the style of MDTraj with Notebooks.

What else?

**Comment by kyleabeauchamp** [comment]
These have all been pulled out into separate issues.
