### ISSUE TITLE
making a computeGeneralExpectations function and wrapping it? 

### ISSUE THREAD

**Issue by mrshirts** [choderalab/pymbar#89]
In the nk branch, I've created a computeGeneralExpectations routine, that takes in I observable arrays and K state observables. In theory, this would mean that there are I*K observables, which means that there are (I*K)^2 terms in the covariance matrix, which is just silly. Instead, this computeGeneralExpectation matrix expects a Sx2 array state_list which describes how many average observables should be computed.

I have demonstrated this by allowing computeExpectations to perform it's functions by calling computeGeneralExpectation for all the heavy lifting. For the state_dependent=False case, the state_list would be [[0,1],[0,2],[0,3]. . . [0,K]], which means that the 0th observable is evaluated at the K different state, for S=K total states. For the state_dependent=True case, the state_list would look like [[0,0],[1,1],[2,2]. . . [K,K]], so there are S=K average observables, with the 0th observable averaged at the 0th state, 1st observable averaged at the 1st state, etc.

Note that this computeGeneralExpectations can easily be used to do the heavy lifting with computeMultipleExpectations, with state list [1,0],[2,0],[3,0]. . . [K,0]], but I haven't done that until people look it everything. It should work just fine for computePerturbedExpectations as well, and possibly computeEntropyandEnthalpy with some tweaking. I'd propose using some version of computeGeneralExpectations to replace a number of the existing repetitive codes eventually.

computeGeneralExpectations can be improved (right now, the u_ln that you add are recomputed even if they are already solved for in the u_kn matrix), but should be a good baseline.

**Comment by kyleabeauchamp** [comment]
AFAIK this is done
